### ISSUE TITLE
Update documentation about contributing to yt on github

### ISSUE THREAD

**Issue by matthewturk** [yt-project/bb-migration#4]
All the documentation needs to be updated to reflect that contributions now happen on GitHub, not bitbucket.

**Comment by lindsayad** [comment]
@MatthewTurk have you made much progress on this? I would be willing to help out on this one.

**Comment by matthewturk** [comment]
I have made basically *no* progress on this.  I'd love the help.

**Comment by lindsayad** [comment]
Alright, unfortunately I'll be out of town tomorrow, Friday, and Monday, but I'll be ready to hammer on it starting Tuesday.

**Comment by lindsayad** [comment]
I'm a little confused...we have the website mercurial repo which appears to have content in it and we have the doc subdirectory in the main yt repo. Is the actual website a blend of this content? My grep searches aren't revealing all the mercurial hits I'm finding on the actual website.

**Comment by matthewturk** [comment]
Ah!  The website has some tooling associated with it that computes the contributors that could be ported.  The doc subdirectory in the main yt repo is the one that needs the work most badly.

**Comment by ngoldbaum** [comment]
Yeah, the documentation is built from the doc folder in the repository and then uploaded to the website. It's not part of the website repo.

**Comment by lindsayad** [comment]
Ah I see, all the hits I was failing to find were in $YT_HG/CONTRIBUTING.rst instead of in the `doc` subdirectory :-)

**Comment by ngoldbaum** [comment]
I think Alex has finished here, see: https://bitbucket.org/yt_analysis/yt/pull-requests/2584

In addition, I updated the rest of the documentation here: https://bitbucket.org/yt_analysis/yt/pull-requests/2590
